baseurl = "https://justingarrison.com"
title = "home"
theme ="hugo-theme-basic"
languageCode = "en-us"
googleAnalytics = "UA-140948948-1"
enableEmoji = true
copyright = "© 2016-2021 Justin Garrison <a href='https://twitter.com/rothgar'>@rothgar</a>."
description = "Personal site and blog of Justin Garrison"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":sign_of_the_horns:"
  # change this!
  twitter = "rothgar"
  images = "img/og-banner.png"
  title = "Justin Garrison dot com"
  description = "Personal site and blog of Justin Garrison"

[Permalinks]
  post = "blog/:slug"

[[params.menu]]
  name = "blog"
  url = "blog/"

[[params.menu]]
  name = "post series"
  url = "series/"

[[params.menu]]
  name = "about"
  url = "about/"

[[params.menu]]
  name = "123 dev newsletter"
  url = "newsletter/"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[markup.goldmark.renderer]
unsafe= true