baseURL = 'https://draft--jgarr.netlify.app/'
languageCode = 'en-us'
title = ' Justin Garrison'
theme = 'blist'

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "© 2016-2022 Justin Garrison @rothgar."
  favicon = "🤘"

  logo = ""

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  #intro
  introTitle =  "Hi, I'm Justin. "
  introSubtitle =  " I'm a developer who works in the cloud and open source. I've helped create Oscar winning movies, build Disney+, and work at AWS. I'm a Linux and Kubernetes nerd who loves to help people."
  introPhoto = "/img/profile.png"

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "Here's where I hang out in social media"
  twitter = "https://twitter.com/rothgar"
  github = "https://github.com/rothgar"
  linkedin = "https://www.linkedin.com/in/justingarrison/"
  tiktok = "https://www.tiktok.com/@justinleegarrison"
  youtube = "https://youtube.com/justingarrison"
  reddit = "https://www.reddit.com/user/xrothgarx"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 3

[[menu.main]]
  name = "Timeline"
  url = "https://timeline.justingarrison.com"
  weight = 4

[[menu.main]]
  name = "Newsletter"
  url = "https://www.123dev.email/"
  weight = 5

[build]
  writeStats = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
