baseurl = "https://justingarrison.com"
title = "home"
siteTitle = "Justin Garrison"
theme = "hugo-theme-basic"
languageCode = "en-us"
image = "/img/og-banner.jpg"
googleAnalytics = "UA-140948948-1"
enableEmoji = true
copyright = "© 2016-2021 Justin Garrison <a href='https://twitter.com/rothgar'>@rothgar</a>."
description = "Articles and links from Justin"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":metal:"
  twitter = "rothgar"
  image = "https://justingarrison.com/img/og-banner.jpg"
  imageAlt = "Two arcade characters with a shipping container and kubernetes logo"
  siteTitle = "Justin Garrison's personal site"
  description = "Articles and links from Justin"

[Permalinks]
  post = "blog/:slug"

[[params.menu]]
  name = "blog"
  url = "blog/"

[[params.menu]]
  name = "about"
  url = "about/"

[[params.menu]]
  name = "newsletter"
  url = "https://123dev.email"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[markup.goldmark.renderer]
unsafe= true