[build]
publish = "public"
command = "npm i && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.104.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "18.10.0"

[context.branch-deploy]
publish = public
command = "npm i && hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.104.2"
NODE_VERSION = "18.10.0"
