[build]
publish = "public"
command = "npm i && hugo --gc"

[context.production.environment]
HUGO_VERSION = "0.104.2"
HUGO_ENV = "production"
NODE_VERSION = "18.10.0"

[context.branch-deploy]
publish = "public"
command = "npm i && hugo -D -F --gc -b $DEPLOY_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.104.2"
NODE_VERSION = "18.10.0"

[[redirects]]
from = "/shares"
to = "/blog"

